### ISSUE TITLE
Question regarding the extension of the sampler for Categorical Distribution

### ISSUE THREAD

**Issue by Habush** [ruqizhang/discrete-langevin#2]
Hi, 

In the recently added code, the extension of the sampler from the binary case to general categorical distributions is implemented. However, looking at the code, I'm having a hard time understanding the implementation. Particularly, in [LangevinSamplerMultiDim](https://github.com/ruqizhang/discrete-langevin/blob/main/CategoricalExample/samplers.py) sampler code, I can't relate what the sampler is doing with what is shown in the paper, esp. Equation (2). 

https://github.com/ruqizhang/discrete-langevin/blob/99c30190f09ff593aaebffdcbabafcfb5a73d34b/CategoricalExample/samplers.py#L54-L61

In above code snippet taken from the step function of the sampler, after calculating the gradient, you then calculate the term `grad_cur` which is using only the first sample (I'm assuming the first dimension is batch dimension) and subtract that from the gradient. I don't understand why the proposal is being calculated like this? Can you please explain?

**Comment by gnobitab** [comment]
Hi Habush,

Thank you for the question.

(1) grad_cur = grad[0:1, range(self.dim), x_cur[0, :]] : We are taking only the first sample because in this example the batch size is 1. It is hardcoded and supposed to change if the batch size is larger than 1. See https://github.com/ruqizhang/discrete-langevin/blob/99c30190f09ff593aaebffdcbabafcfb5a73d34b/CategoricalExample/sample_categorical_distribution.py#L76

(2) For the computation, we are implementing Eq. (2) in the paper, where first_term refers to 
![image](https://user-images.githubusercontent.com/1157982/204450389-8147dc7b-2844-4e4e-82c8-f8bc3dbe263a.png)
and second term refers to 
![image](https://user-images.githubusercontent.com/1157982/204450433-ccc82d12-98f6-40d5-be2e-0943ad749352.png)

For the first term, since \theta_i and \theta_i^' are all one-hot vectors, it becomes $\nabla U(\theta)_i \theta_i' - \nabla U(\theta)_i \theta_i$, where only the i'-th and i-th element is non-zero, which then becomes the (grad - grad_cur) term. 

For the second term, since \theta_i and \theta_i^' are all one-hot vectors, ||\theta_i - \theta'_i||=0, when \theta'_i = \theta_i and ||\theta_i - \theta'_i||=1, when \theta'_i \neq \theta_i.

Hope that helps!

**Comment by Habush** [comment]
Hi @gnobitab , thank you for your explanation! It is clearer now. I have only one confusion left :) 
In your explanation of the first term, you said:

> For the first term, since $\theta_i$ and $\theta_i^{'}$ are all one-hot vectors, it becomes $\nabla U(\theta)_i\theta_i^{'}  - \nabla U(\theta)_i\theta_i$
, where only the i'-th and i-th element is non-zero, which then becomes the (grad - grad_cur) term.

But at this stage in the sampler we don't know the value of $\theta_i{'}$ (or at least there is no definition of it in the code at this point) so when you say $\nabla U(\theta)_i\theta_i^{'}  - \nabla U(\theta)_i\theta_i$ is (grad - grad_curr) I think you are assuming  that grad = $\nabla U(\theta)_i\theta_i^{'}$. I don't understand how this assumption works? Or am I missing something here?

Also, a very slight correct, I think at this [line](https://github.com/ruqizhang/discrete-langevin/blob/99c30190f09ff593aaebffdcbabafcfb5a73d34b/CategoricalExample/samplers.py#L57), in should be `2*self.step_size` in the denominator

**Comment by gnobitab** [comment]
Hi Habush,

To determine the next sample, $\theta'_i$ loops over all the possible categories for each dimension. So we need a matrix in the shape of (bs * dim * num_of_categories), where each element is $\nabla U(\theta)_i \theta_i' - \nabla U(\theta)_i \theta_i$ and $\theta'_i$ loops over all the categories. Since $\theta'_i$ are one-hot vectors, $\nabla U(\theta)_i \theta'_i$ in fact extracts the i-th dimension of grad. Similarly, grad_cur = $\nabla U(\theta)_i \theta_i$ is also the i-th dimension of grad with the current sampled categories (L54). 

L54-55 actually implements this with broadcasting. In L54, $\nabla U(\theta)_i \theta_i$ is computed by extracting the columns corresponds to the the current sample. In L55, $\nabla U(\theta)_i \theta_i' - \nabla U(\theta)_i \theta_i$ for all possible $i'$ by subtracting grad_cur from grad (note that, each dimension in grad is $\nabla U(\theta)_i \theta'_i$).

**Comment by gnobitab** [comment]
Also, thank you for the correction! We'll check that later!

**Comment by Habush** [comment]
Hi @gnobitab,

Thank you so much! After Revisiting section 4 of the paper and reading your comment above, now it is clear!
